apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: keycloak
  
  source:
    # This will be overridden by Kustomize overlay with user's fork URL
    repoURL: ${REPO_URL}
    # For production, use tags instead of branches
    targetRevision: ${PROD_TARGET_REVISION}
    path: helm-chart
    
    helm:
      # Use production values file
      valueFiles:
        - values-prod.yaml
      
      # Additional values overrides for production
      values: |
        replicaCount: 3
        
        image:
          pullPolicy: IfNotPresent
        
        ingress:
          enabled: true
          hostname: keycloak.yourdomain.com
          tls:
            enabled: true
            secretName: keycloak-tls
        
        postgresql:
          enabled: true
          auth:
            username: keycloak
            database: keycloak_prod
          primary:
            persistence:
              enabled: true
              size: 10Gi
        
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 1Gi
        
        autoscaling:
          enabled: true
          minReplicas: 3
          maxReplicas: 10
          targetCPUUtilizationPercentage: 80
        
        # Production-specific settings
        health:
          enabled: true
        
        metrics:
          enabled: true
      
      releaseName: keycloak-prod
  
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak-prod
  
  syncPolicy:
    # More conservative sync policy for production
    automated:
      prune: false       # Don't auto-delete in production
      selfHeal: false    # Don't auto-fix in production (manual intervention)
    
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore if HPA changes replica count