apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base/keycloak-prod.yaml

patches:
  - target:
      kind: Application
      name: keycloak-prod
    patch: |-
      - op: replace
        path: /spec/source/repoURL
        value: https://github.com/JOELNATHAN544/keycloak-helm-chart
      - op: replace
        path: /spec/source/targetRevision
        value: v1.0.0

commonLabels:
  environment: production
  managed-by: argocd
